const TYPING = 'TYPING';
const SHORTCUTS = 'SHORTCUTS';
const REPLACE = 'REPLACE';
const COMMAND = 'COMMAND';
const GREP = 'GREP';
const FILEFINDER = 'FILEFINDER';
const VISUAL = 'VISUAL';
const VISUALLINE = 'VISUALLINE';
const VISUALBLOCK = 'VISUALBLOCK';
const HISTORY = 'HISTORY';
const SEARCH = 'SEARCH';
const MULTICURSOR = 'MULTICURSOR';

export {
    TYPING,
    SHORTCUTS,
    REPLACE,
    COMMAND,
    GREP,
    FILEFINDER,
    VISUAL,
    VISUALLINE,
    VISUALBLOCK,
    HISTORY,
    SEARCH,
    MULTICURSOR
};