const COMMAND = 'COMMAND';
const FILEEXPLORER = 'FILEEXPLORER';
const FILEFINDER = 'FILEFINDER';
const GREP = 'GREP';
const HISTORY = 'HISTORY';
const MULTICURSOR = 'MULTICURSOR';
const SEARCH = 'SEARCH';
const SHORTCUTS = 'SHORTCUTS';
const TYPING = 'TYPING';
const VISUAL = 'VISUAL';
const VISUALBLOCK = 'VISUALBLOCK';
const VISUALLINE = 'VISUALLINE';

export {
    COMMAND,
    FILEEXPLORER,
    FILEFINDER,
    GREP,
    HISTORY,
    MULTICURSOR,
    SEARCH,
    SHORTCUTS,
    TYPING,
    VISUAL,
    VISUALBLOCK,
    VISUALLINE,
};
